# Generated by Django 4.1.3 on 2023-10-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DormCare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('complaints', models.CharField(max_length=255)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
